blank_issues_enabled: false
contact_links:
  - name: Questions and Discussion
    url: https://github.com/orgs/uncord-chat/discussions
    about: Ask questions and discuss ideas in GitHub Discussions.
